apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: web-svc-canary
  namespace: emojivoto
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-svc
status:
  loadBalancer: {}
